# Generated by Django 4.2.13 on 2024-06-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0002_favoritelist_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritelist',
            name='description',
        ),
    ]
