# Generated by Django 4.2.13 on 2024-06-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0003_remove_favoritelist_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteList',
        ),
    ]
